title:              Adam & Scarlett
email:              adamjlee5@aol.com
description:        Wedding Day 24.06.2025
author:             Adam
baseurl:            "/Adam-and-Scarlett-2025"
url:                "https://startbootstrap.github.io"

# Social Profiles
facebook_username:  StartBootstrap


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
